
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvoyuckytcuusqszcxom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2b3l1Y2t5dGN1dXNxc3pjeG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzE4ODksImV4cCI6MjA1ODgwNzg4OX0.B1hFFGbWgRnKgz8JbFyQVj7Y8ROqqAgcaxTEl2pZgAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
